### ISSUE TITLE
Collection of issues in other tools we depend on

### ISSUE THREAD

**Issue by nkuehn** [nkuehn/sphere-icecat-importer#2]
- [x]  https://github.com/sphereio/sphere-category-sync/issues/12  (continue on problems in category import)
- [ ] https://github.com/sphereio/sphere-node-product-csv-sync/issues/56  csv-product-sync fails hard due to CSV file size.
- [x] https://github.com/sphereio/sphere-node-product-csv-sync/issues/52  (product csv import should be able to map categories by external ID)
- [x] https://github.com/sphereio/sphere-node-product-csv-sync/issues/83 (category references broken)
- [ ] find a web frontend that supports deeply nested category structures

Workaround possible / not a hard blocker (it would just be nice if the stuff would take less than the current 2-3 hours to run):
- [ ] https://github.com/sphereio/sphere-category-sync/issues/6 (category import requires tree-ordered import files)  -- Workaround possible by doing a two-pass import, first flat and then update with tree info)
- [ ] https://github.com/sphereio/sphere-node-product-csv-sync/issues/37  (product csv import should detect variants itself)
- [ ] https://github.com/sphereio/csv-mapper/issues/1  (csv-mapper requires a group column, but that cannot be created in the same run so we have to run through the mapping two consecutive times with separate mappings)
- [ ] https://github.com/sphereio/csv-mapper/issues/5  (csv-mapper bombs node memory with many external csv lookups)

**Comment by nkuehn** [comment]
@mmoelli I cleaned up this list and added the csv importer issue.
